---
- name: Update web server
  hosts: web
  tasks:
    - name: Latest httpd package installed
      yum:
        name: httpd
        state: latest
      notify:
        - Restart httpd

  handlers:
    - name: Restart httpd
      service: 
        name: httpd
        enabled: yes
        state: restarted